CREATE TABLE users (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       username varchar(255) NOT NULL,
       user_status varchar(255) NULL,
       CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE quotes (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       quote_id UUID NOT NULL,
       author varchar(255),
       category varchar(255),
       image_url varchar(255) NOT NULL,
       like_count BIGINT DEFAULT 0,
       share_count BIGINT DEFAULT 0,
       CONSTRAINT quotes_pkey PRIMARY KEY (id)
);

CREATE TABLE author (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       name varchar(255),
       CONSTRAINT author_pkey PRIMARY KEY (id)
);

CREATE TABLE category (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       name varchar(255),
       CONSTRAINT category_pkey PRIMARY KEY (id)
);